backend:
  name: github
  repo: flavianunes/fluvixx.dev

media_folder: static/img
public_folder: /img  

collections:
  - name: blog
    label: Blog
    folder: "content/blog"
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - {name: tags, label: Tags, widget: list}
      - {name: live, label: Live Version}
      - {name: github, label: Github Link}
      - { name: body, label: Body, widget: markdown }
